# Generated by Django 5.1.3 on 2024-12-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_dish_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "Dishes"},
        ),
    ]
